# Define the location mapping dictionary
location_mapping = {
    'Cairo Festival City Mall': 'Cairo Festival City',
    'Cairo': 'Cairo',
    'Giza, Cairo': 'Giza',
    'New Cairo': 'New Cairo',
    'Maadi, Zamalek': 'Maadi',
    '12 Mohamed Anis St., Zamalek': 'Zamalek',
    '15 Emad El-Deen, Downtown': 'Downtown',
    'Islamic Cairo': 'Cairo',
    'Mall of Egypt, 6th of October City': 'Mall of Egypt',
    'Obour City': 'Obour City',
    'Zamalek, Cairo': 'Zamalek',
    'The Field Maadi Sports Community Club': 'Maadi',
    'Point 90 Mall, New Cairo & Avenue Mall, Obour City': 'New Cairo',
    'Cairo Festival City, 5th Settlement': 'Cairo Festival City',
    'Inside Mazar Mall, 6th of October City': 'Mazar Mall',
    'Gate 1, Al-Hezam El-Akhdar, 6th of October': '6th of October City',
    'Dandy Mega Mall, 6th of October City': 'Dandy Mega Mall',
    'MOVING TO A NEW LOCATION': 'Unknown Location',
    'New Cairo Club, 5th Settlement': 'New Cairo',
    'Various locations in Maadi': 'Maadi',
    '54 Mohi El-Din Abo Al Ezz street, Dokki': 'Dokki',
    'Al Guezira Plaza, Sheikh Zayed': 'Sheikh Zayed',
    '104 Omar Ebn El-Khattab Street, Heliopolis': 'Heliopolis',
    '34 Street 206, Degla – Maadi': 'Maadi',
    '56 Al Bostan St, Sheikh Zayed': 'Sheikh Zayed',
    'B311, 90th Street, New Cairo': 'New Cairo',
    '3 Skies Plaza, 5th Settlement': 'New Cairo',
    '5 Abou El-Feda St., Zamalek': 'Zamalek',
    '4, 216 Street, Victory Square – Maadi': 'Maadi',
    'City Square Mall, Al Rehab': 'Al Rehab',
    '258 A, Anas Ebn Malek Street – New Cairo': 'New Cairo',
    'Maadi City Center, Cairo Festival City Mall, Mall of Egypt': 'Maadi City Center',
    'Americana Plaza – Sheikh Zayed': 'Sheikh Zayed',
    'Dandy Mega Mall – Cairo/Alex Desert Road': 'Dandy Mega Mall',
    'Mirage Mall – Suez Road & Mall of Arabia, 6th of October City': 'Mirage Mall',
    'Dandy Mega Mall – Cairo/Alex Desert Road, 6th of October City': 'Dandy Mega Mall',
    'Salah Salem Street, Heliopolis': 'Heliopolis',
    '3 Skies Plaza, 5th Settlement – New Cairo': 'New Cairo',
    '46 El-Nozha, Heliopolis': 'Heliopolis',
    'Street no. 9 in front of Pizza Hut – Maadi': 'Maadi',
    '5th Settlement, Concord Plaza Mall': 'Concord Plaza Mall',
    '10 Etehaad Al Mohamin St., Garden City': 'Garden City',
    '1 Palestine St., El Bandar Mall – Maadi': 'Maadi',
    '8 Sesostris street, Heliopolis': 'Heliopolis',
    'Various locations': 'Multiple Locations',
    'Palm Strip Mall, 6th of October City': 'Palm Strip Mall',
    'Obour City, Cairo': 'Obour City',
    'Maryouteya Road, Giza': 'Giza',
    'Cairo Festival City, Cairo': 'Cairo Festival City',
    '30 km southwest of Cairo': 'Cairo',
    'Abu Sir, Cairo': 'Abu Sir',
    'Porto Cairo, Cairo': 'Porto Cairo',
    'Various locations in Cairo': 'Multiple Locations',
    'El-Gamaleya, Cairo': 'El-Gamaleya',
    'Mall of Arabia, Cairo': 'Mall of Arabia',
    'Heliopolis, Cairo': 'Heliopolis',
    'Nile River, Cairo': 'Cairo',
    'City Stars Mall, Cairo': 'City Stars Mall',
    'Villa Pax, Imbaba, Cairo': 'Imbaba'
}